# Generated by Django 2.1.1 on 2018-09-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_lance', models.CharField(max_length=150, verbose_name='Tipo do lance')),
                ('data_lance', models.DateTimeField(verbose_name='Data e hora do lance')),
            ],
        ),
        migrations.CreateModel(
            name='Locais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do local')),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('MG', 'Minas Gerais'), ('SP', 'São Paulo'), ('AC', 'Acre'), ('ES', 'Espirito Santo'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('GO', 'Goias'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor do aluguel')),
            ],
        ),
        migrations.CreateModel(
            name='Partidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_partida', models.DateTimeField(verbose_name='Data e hora do inicio da partida')),
                ('fim_partida', models.DateTimeField(verbose_name='Data e hora do fim da partida')),
                ('placar1', models.IntegerField(verbose_name='Placar do time 1')),
                ('placar2', models.IntegerField(verbose_name='Placar do time 2')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='efut.Locais')),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Time')),
                ('pvencidas', models.IntegerField(null=True, verbose_name='Partidas vencidas')),
                ('pperdidas', models.IntegerField(null=True, verbose_name='Partidas perdidas')),
                ('pjogadas', models.IntegerField(null=True, verbose_name='Partidas jogadas')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('idade', models.DateField(verbose_name='Data de nascimento')),
                ('criado_em', models.DateTimeField(auto_now=True)),
                ('fk_times', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='efut.Times')),
            ],
        ),
        migrations.AddField(
            model_name='partidas',
            name='time1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time1', to='efut.Times'),
        ),
        migrations.AddField(
            model_name='partidas',
            name='time2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time2', to='efut.Times'),
        ),
        migrations.AddField(
            model_name='lances',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='efut.Partidas'),
        ),
        migrations.AddField(
            model_name='lances',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='efut.Usuarios'),
        ),
    ]
